### PR TITLE
fix: remove panic from did_sidetree_steps

### LINKED ISSUE #17: remove panic from did_sidetree_steps

### PR DESCRIPTION
**Pull request by fqutishat**
closes #17

Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

File: test/bddtests/did_sidetree_steps.go [hunk 1]
```diff
@@ -74,11 +74,6 @@ func (d *DIDSideSteps) checkErrorResp(errorMsg string) error {
 
 func (d *DIDSideSteps) checkSuccessResp(msg string) error {
 	if d.resp.ErrorMsg != "" {
-		documentHash, err := docutil.CalculateID(didDocNamespace, d.reqEncodedDIDDoc, sha2256)
```
Comment (rolsonquadras) [inline test/bddtests/did_sidetree_steps.go]: The title says 'remove panic'. but changes show other 2 lines removed. was this intentional ?

Comment (fqutishat) [reply test/bddtests/did_sidetree_steps.go]: yes
